pc(department).
assign(department,ua1)
assign(department,ua2)
assign(department,ua4)
assign(department,ua5)
assign(department,oa1)
assign(department,oa2)
assign(department,oa4)
assign(department,oa5)
oa(oa5).
assign(oa5,oa6)
oa(oa6).
assign(oa6,oa7)
oa(oa7).
assign(oa7,o1)
o(o1).
oa(oa4).
assign(oa4,oa6)
oa(oa2).
assign(oa2,oa3)
oa(oa3).
assign(oa3,oa7)
oa(oa1).
assign(oa1,oa3)
ua(ua5).
assign(ua5,ua6)
association(ua5,oa5,PERMISSION0)
ua(ua6).
assign(ua6,ua7)
ua(ua7).
assign(ua7,u1)
u(u1).
association(u1,o1,PERMISSION1)
prohibition(u1,o1,PERMISSION2)
ua(ua4).
assign(ua4,ua6)
association(ua4,oa5,PERMISSION0)
association(ua4,oa4,PERMISSION4)
association(ua4,oa2,PERMISSION4)
ua(ua2).
assign(ua2,ua3)
association(ua2,oa2,PERMISSION0)
ua(ua3).
ua(ua1).
assign(ua1,ua3)
assign(ua1,u2)
association(ua1,oa4,PERMISSION1 PERMISSION2)
u(u2).
prohibition(u2,oa7,PERMISSION1)
